import random
a = random.randint(0,20)
b = random.randint(0,20)
c = random.randint(0,20)
d = random.randint(0,20)
x = random.randint(0,100)
y = random.randint(75,140)

print ("het aantal HP dat je hebt is:")
print (a)
print ("jou aantal stamina is:")
print (b)
print ("je strenght is:")
print (c)
print ("je magic is:")
print (d)
print ("je iq is:")
print (y)
print ("jouw actractiveness is:")
print (x)